version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: geo_db
    environment:
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_password
      POSTGRES_DB: geo_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/Senate.sql:/docker-entrypoint-initdb.d/Senate.sql
      - ./sql/BOE.sql:/docker-entrypoint-initdb.d/BOE.sql
      - ./sql/Congressional.sql:/docker-entrypoint-initdb.d/Congressional.sql
      - ./sql/Assembly.sql:/docker-entrypoint-initdb.d/Assembly.sql

  django:
    build:
      context: ./Geo
    container_name: geo_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Geo:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=geo_db
      - POSTGRES_USER=geo_user
      - POSTGRES_PASSWORD=geo_password
      - POSTGRES_HOST=db
    depends_on:
      - db

  react:
    build:
      context: "./react-front-end-wip/"
      dockerfile: ./Dockerfile
    container_name: geo_react
    ports:
      - "5173:5173"
    volumes:
      - ./react-front-end-wip/Geo_app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  postgis_data:
