version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.4
    container_name: geo_db
    environment:
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_password
      POSTGRES_DB: geo_db
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geo_user -d geo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./Geo
    container_name: geo_django
    # need to add this retry behavior because pgsql restarts by default when you run .sql scripts on-startup
    # issue is: if the db restarts while Django tries to connect, we fail to connect the backend to the DB
    command: >
      sh -c "while ! pg_isready -h db -p 5432 > /dev/null 2>&1; do
              echo 'Waiting for Postgres...';
              sleep 1;
            done;
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Geo:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=geo_db
      - POSTGRES_USER=geo_user
      - POSTGRES_PASSWORD=geo_password
      - POSTGRES_HOST=db
    networks:
      - app_network
    depends_on:
      - db

  react:
    build:
      context: "./react-front-end-wip/"
      dockerfile: ./Dockerfile
    container_name: geo_react
    ports:
      - "5173:5173"
    volumes:
      - ./react-front-end-wip/Geo_app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

volumes:
  postgis_data:

networks:
  app_network:
    driver: bridge

