# Generated by Django 4.2.16 on 2024-10-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GIS',
            fields=[
                ('gis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HPSA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('hpsa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('input_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=100)),
                ('alt_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MSSA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('mssa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenateDistrict',
            fields=[
                ('senate_district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.districts')),
            ],
        ),
        migrations.CreateModel(
            name='RNSA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('rnsa_id', models.AutoField(primary_key=True, serialize=False)),
                ('mssa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.mssa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryCare',
            fields=[
                ('primary_care_id', models.AutoField(primary_key=True, serialize=False)),
                ('hpsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.hpsa')),
            ],
        ),
        migrations.CreateModel(
            name='PCSA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('pcsa_id', models.AutoField(primary_key=True, serialize=False)),
                ('mssa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.mssa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MUP',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('mup_id', models.AutoField(primary_key=True, serialize=False)),
                ('mssa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.mssa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MUA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('mua_id', models.AutoField(primary_key=True, serialize=False)),
                ('mssa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.mssa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('mental_health_id', models.AutoField(primary_key=True, serialize=False)),
                ('hpsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.hpsa')),
            ],
        ),
        migrations.CreateModel(
            name='LASPA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('laspa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HSA',
            fields=[
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('update_process', models.CharField(max_length=100)),
                ('hsa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HCF',
            fields=[
                ('hcf_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
        ),
        migrations.AddField(
            model_name='gis',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.input'),
        ),
        migrations.CreateModel(
            name='FQHC',
            fields=[
                ('fqhc_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=100)),
                ('gis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis')),
            ],
        ),
        migrations.CreateModel(
            name='DSH',
            fields=[
                ('dsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('consumer', models.CharField(max_length=100)),
                ('update_frequency', models.CharField(max_length=100)),
                ('hcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.hcf')),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='gis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.gis'),
        ),
        migrations.CreateModel(
            name='DentalHealth',
            fields=[
                ('dental_health_id', models.AutoField(primary_key=True, serialize=False)),
                ('hpsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.hpsa')),
            ],
        ),
        migrations.CreateModel(
            name='CongressionalDistrict',
            fields=[
                ('congressional_district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.districts')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyDistrict',
            fields=[
                ('assembly_district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geo.districts')),
            ],
        ),
    ]
