# Generated by Django 4.2.16 on 2025-01-29 01:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyDistrict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_number', models.IntegerField()),
                ('area', models.FloatField()),
                ('members', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('cvap_19', models.IntegerField()),
                ('hsp_cvap_1', models.IntegerField()),
                ('doj_nh_blk', models.IntegerField()),
                ('doj_nh_asn', models.IntegerField()),
                ('nh_wht_cva', models.IntegerField()),
                ('ideal_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('f_deviatio', models.FloatField()),
                ('f_cvap_19', models.FloatField()),
                ('f_hsp_cvap', models.FloatField()),
                ('f_doj_nh_b', models.FloatField()),
                ('f_doj_nh_a', models.FloatField()),
                ('f_nh_wht_c', models.FloatField()),
                ('district_n', models.IntegerField(null=True)),
                ('district_label', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CongressionalDistrict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_number', models.IntegerField()),
                ('area', models.FloatField()),
                ('members', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('cvap_19', models.IntegerField()),
                ('hsp_cvap_1', models.IntegerField()),
                ('doj_nh_blk', models.IntegerField()),
                ('doj_nh_asn', models.IntegerField()),
                ('nh_wht_cva', models.IntegerField()),
                ('ideal_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('f_deviatio', models.FloatField()),
                ('multiple_f', models.CharField(blank=True, max_length=50, null=True)),
                ('f_cvap_19', models.FloatField()),
                ('f_hsp_cvap', models.FloatField()),
                ('f_doj_nh_b', models.FloatField()),
                ('f_doj_nh_a', models.FloatField()),
                ('f_nh_wht_c', models.FloatField()),
                ('district_label', models.CharField(blank=True, max_length=50, null=True)),
                ('district_n', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SenateDistrict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_number', models.IntegerField()),
                ('area', models.FloatField()),
                ('members', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('cvap_19', models.IntegerField()),
                ('hsp_cvap_1', models.IntegerField()),
                ('doj_nh_ind', models.IntegerField(null=True)),
                ('doj_nh_blk', models.IntegerField()),
                ('doj_nh_asn', models.IntegerField()),
                ('nh_wht_c', models.IntegerField()),
                ('ideal_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('f_deviation', models.FloatField()),
                ('f_cvap_19', models.FloatField()),
                ('f_hsp_cvap_1', models.FloatField()),
                ('f_doj_nh_b', models.FloatField()),
                ('f_doj_nh_a', models.FloatField()),
                ('f_nh_wht_c', models.FloatField()),
                ('district_label', models.CharField(blank=True, max_length=50, null=True)),
                ('multiple_f', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
