# Generated by Django 4.2.16 on 2025-04-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminerrors',
            name='files_name',
            field=models.TextField(default='Untraceable file name'),
        ),
        migrations.AddField(
            model_name='adminerrors',
            name='line_number',
            field=models.TextField(default='Untraceable line number'),
        ),
    ]
