# Generated by Django 4.2.16 on 2025-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminErrors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_code', models.IntegerField()),
                ('error_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
