# Generated by Django 4.2.16 on 2025-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpsa_dentalhealthshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hpsa_dentalhealthshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hpsa_mentalhealthshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hpsa_mentalhealthshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hpsa_primarycareshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hpsa_primarycareshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
