# Generated by Django 4.2.16 on 2025-04-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
