# Generated by Django 4.2.16 on 2025-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hpsa_dentalhealthshortagearea_hpsa_estimated_served_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpsa_dentalhealthshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpsa_dentalhealthshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpsa_mentalhealthshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpsa_mentalhealthshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpsa_primarycareshortagearea',
            name='hpsa_estimated_served_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hpsa_primarycareshortagearea',
            name='hpsa_estimated_underserved_population',
            field=models.BigIntegerField(null=True),
        ),
    ]
