# Generated by Django 4.2.16 on 2025-03-15 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthServiceArea',
            fields=[
                ('count', models.IntegerField()),
                ('hsa_number', models.IntegerField(primary_key=True, serialize=False)),
                ('hsa_code', models.CharField(max_length=5)),
                ('hsa_name', models.CharField(max_length=50)),
                ('area_sqmi', models.FloatField()),
                ('pop2000', models.FloatField()),
                ('popdensity', models.FloatField()),
                ('shape_star', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LAServicePlanningArea',
            fields=[
                ('spa', models.IntegerField(primary_key=True, serialize=False)),
                ('spa_num', models.CharField(max_length=10)),
                ('spa_name', models.CharField(max_length=25)),
                ('shape_star', models.FloatField()),
                ('shape_stle', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalServiceStudyArea',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=5)),
                ('countyfp', models.CharField(max_length=5)),
                ('county_nm', models.CharField(max_length=50)),
                ('tractce', models.CharField(max_length=10)),
                ('geoid', models.CharField(max_length=25)),
                ('aland', models.BigIntegerField()),
                ('awater', models.BigIntegerField()),
                ('asqmi', models.FloatField()),
                ('intptlat', models.FloatField()),
                ('intptlon', models.FloatField()),
                ('mssaid', models.CharField(max_length=10)),
                ('mssanm', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=10)),
                ('totalpovpo', models.IntegerField()),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryCareShortageArea',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('unit_count', models.IntegerField()),
                ('cnty_fips', models.CharField(max_length=10)),
                ('mssa_id', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=25)),
                ('area_sqmi', models.FloatField()),
                ('mssa_count', models.CharField(max_length=40)),
                ('mssa_name', models.CharField(max_length=200)),
                ('total_popu', models.IntegerField()),
                ('est_physic', models.FloatField()),
                ('est_fnppa', models.FloatField()),
                ('est_provid', models.FloatField()),
                ('provider_r', models.FloatField()),
                ('score_prov', models.IntegerField()),
                ('pop_fpl', models.IntegerField()),
                ('pct_fpl', models.FloatField()),
                ('score_pove', models.IntegerField()),
                ('score_tota', models.IntegerField()),
                ('pcsa', models.CharField(max_length=5)),
                ('effective', models.DateField()),
                ('shape_are', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredNurseShortageArea',
            fields=[
                ('rn_area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trial_rn_a', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('rn_area_na', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('rn_lic', models.IntegerField()),
                ('rm_emprate', models.FloatField()),
                ('employed_r', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('target_rat', models.IntegerField()),
                ('rnsa', models.CharField(max_length=5)),
                ('severity', models.CharField(max_length=10, null=True)),
                ('effective', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
