# Generated by Django 4.2.16 on 2025-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_healthservicearea_laserviceplanningarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='totalpovpo',
            field=models.BigIntegerField(),
        ),
    ]
