# Generated by Django 4.2.16 on 2025-03-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apikey_key'),
        ('api', '0003_visitortracking_delete_usertracking'),
    ]

    operations = [
    ]
