# Generated by Django 4.2.16 on 2025-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medicalservicestudyarea_totalpovpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='fid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
