# Generated by Django 4.2.16 on 2025-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_medicalservicestudyarea_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='aland',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='awater',
            field=models.FloatField(),
        ),
    ]
