# Generated by Django 4.2.16 on 2025-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medicalservicestudyarea_aland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='county_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='countyfp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='definition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='geoid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='mssaid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='mssanm',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='statefp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='tractce',
            field=models.CharField(max_length=20),
        ),
    ]
