# Generated by Django 4.2.16 on 2025-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_medicalservicestudyarea_county_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='definition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='mssaid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalservicestudyarea',
            name='mssanm',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
