# Generated by Django 4.2.16 on 2025-03-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_overridelocation'),
        ('api', '0008_alter_medicalservicestudyarea_definition_and_more'),
    ]

    operations = [
    ]
