# Generated by Django 4.2.16 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250318_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='6552c808daefd6e6fcc607d21623bf136251db8b0976123e41dcca159b5d5763', max_length=64, unique=True),
        ),
    ]
