# Generated by Django 4.2.16 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_apikey_ip_address_apikey_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='561d3b446720deb2d38decb29bebaedfe7c88c93386436861f32ef38784e4c83', max_length=64, unique=True),
        ),
    ]
