# Generated by Django 4.2.16 on 2025-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='15d32c9d474ddd32efcba9fba5d63edd19a36f6fa1ece44c560bc6c056df628e', max_length=64, unique=True),
        ),
    ]
