# Generated by Django 4.2.16 on 2025-03-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='fa708fdce2cd2cbcc6155b015281a19eecb826b0e3efaeb125102b831f48d18d', max_length=64, unique=True),
        ),
    ]
