import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./header/header"; // Import the Header component
import Footer from "./footer/footer"; // Import the Footer component

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the Next.js app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Main layout component for the app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render Header */}
        <Header />
        {/* Main Content */}
        <main>{children}</main>
        {/* Render Footer */}
        <Footer />
      </body>
    </html>
  );
}
